version: '3.7'

services:

  jenkins:
    build: ./jenkins
    restart: unless-stopped
    container_name: jenkins-blueocean
    #privileged: true
    volumes:
      - ./jenkins/certs:/certs/client:ro
      - ./jenkins/data:/var/jenkins_home
      - ./var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: ${JAVA_OPTS}
      MY_NAME: ${MY_NAME}
      DOCKER_HOST: ${DOCKER_HOST}
      DOCKER_CERT: ${DOCKER_CERT}
      DOCKER_TLS_VERIFY: ${DOCKER_TLS_VERIFY}
    ports:
      - '8080:8080'
      - '50000:50000'
      - "3375:2375"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2G'
    networks:
      - WIC_devops_net


volumes:
  jenkins: {}
  sonarqube: {}

networks:
  WIC_devops_net: {}
